version: "3"

services:
  flarum:
    image: mondedie/flarum:stable
    container_name: flarum
    env_file:
      - ./flarum.env   # 创建一个flarum.env
    volumes:   # 数据映射到本地，数据不会因为Docker停止而丢失
      - ./assets:/flarum/app/public/assets
      - ./extensions:/flarum/app/extensions
      - ./storage/logs:/flarum/app/storage/logs
      - ./nginx:/etc/nginx/flarum
    ports:
      - 8080:8888   # 左边的8080可以自己调整端口号，右边的8888不要改
    restart: unless-stopped
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=AhE6aMvzySjgYMTpkt5
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=AhE6aMvzySjgYMTpkt5
    volumes:
      - /root/data/docker_data/flarum/docker/mysql/db:/var/lib/mysql  # 数据映射到本地，数据不会因为Docker停止而丢失
    restart: unless-stopped